#!/bin/bash
# Auto-generated by WALLCTL v3
# Default: Nissan Skyline R34 (DP-1) + GTA Sunset (HDMI-A-1)

pkill -f -9 mpvpaper
pkill -f -9 linux-wallpaperengine
sleep 1

MPV_OPTS="no-audio loop hwdec=auto scale=bilinear interpolation=no video-sync=display-resample panscan=1.0"

mpvpaper -o "$MPV_OPTS" DP-1 "/home/trinity/.local/share/Steam/steamapps/workshop/content/431960/2951143760/skyline r34 by visualdon.mp4" &
sleep 0.1
mpvpaper -o "$MPV_OPTS" HDMI-A-1 "/home/trinity/.local/share/Steam/steamapps/workshop/content/431960/780034130/GTA Sunset.mp4" &
