# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# ######## Window rules ########

# Fenêtres tuilées: 100% actif, 90% inactif (override = absolu)
windowrule = opacity 0.95 override 0.90 override, match:class ^kitty$
windowrule = opacity 0.95 override 0.90 override, match:class ^cursor$
windowrule = opacity 0.95 override 0.90 override, match:class ^google-chrome$
windowrule = opacity 0.95 override 0.90 override, match:class ^discord$
windowrule = opacity 0.95 override 0.90 override, match:class ^Spotify$
windowrule = opacity 0.95 override 0.90 override, match:class ^steam$
windowrule = opacity 0.95 override 0.90 override, match:class ^Claude$
