# This file sources other files in `hyprland` and `custom` folders
# You wanna add your stuff in files in `custom`

$qsConfig = ii
exec = hyprctl dispatch submap global # DO NOT REMOVE THIS OR YOU WON'T BE ABLE TO USE ANY KEYBIND
submap = global # This is required for catchall to work

# Environment variables
source=hyprland/env.conf
source=custom/env.conf

# Defaults
source=hyprland/execs.conf
source=hyprland/general.conf
source=hyprland/rules.conf
source=hyprland/colors.conf
source=hyprland/keybinds.conf

# Custom 
source=custom/execs.conf
source=custom/general.conf
source=custom/rules.conf
source=custom/keybinds.conf

# nwg-displays support
source=workspaces.conf
source=monitors.conf

# Trae clipboard (sans daemon auto-sync)
bind = SUPER_SHIFT, C, exec, trae-copy
bind = SUPER_SHIFT, V, exec, trae-paste

# XWayland support
env = DISPLAY,:1
env = GDK_BACKEND,wayland,x11
env = QT_QPA_PLATFORM,wayland;xcb
env = SDL_VIDEODRIVER,wayland
env = CLUTTER_BACKEND,wayland

# XWayland
xwayland {
    force_zero_scaling = true
}
source = ~/.config/hypr/nvidia.conf
